"""
Purpose:  Quarto project scaffolding for the publication site. Emits the
          project config, theme and navigation, and copies report assets into
          the site worktree with a recorded checksum so stage 11 can prove the
          published copy still matches the source.
Task:     Publication programme -- BCCh regional data
Inputs:   lib.families (navigation is derived, never hand-listed)
Outputs:  files under the site worktree
Created:  2026-08-26
Updated:  2026-08-26
Owner:    dpolancon
"""

from __future__ import annotations

import hashlib
import shutil
from pathlib import Path

from lib import families as families_lib
from lib.paths import (
    SITE_BASE_URL,
    SITE_HOST,
    SITE_HOST_LINKS,
    SITE_HOST_NOMBRE,
)

SITE_TITLE = "Renta espacial y renta de recursos"
SITE_SUBTITLE = (
    "Revisión multiescalar de la Base de Datos Estadísticos del Banco "
    "Central de Chile"
)

# Directories the generator owns outright. Anything here is regenerated on
# every run, so nothing in them should ever be hand-edited -- stage 11 checks.
GENERATED_DIRS = ("reportes", "notas", "briefings", "datos", "assets")


def sha256(path: Path) -> str:
    """Hex digest of a file, used to prove a published asset is unmodified."""
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def quarto_yml(published: list[dict]) -> str:
    """Project config. The navbar is derived from the published report list."""
    nav = "\n".join(
        f"          - text: \"{r['nav_label']}\"\n"
        f"            href: reportes/{r['slug']}.qmd"
        for r in published
    )
    return f"""# GENERATED by scripts/10_generate_site.py -- do not edit by hand.
# Navigation is derived from lib/families.py so the menu cannot drift out of
# step with what has actually been published.
project:
  type: website
  output-dir: docs

website:
  title: "{SITE_TITLE}"
  description: "{SITE_SUBTITLE}"
  # Absolute base: the section is served from a subpath of the personal site,
  # and the sitemap and search index cannot resolve without it.
  site-url: "{SITE_BASE_URL}"
  reader-mode: true
  navbar:
    left:
      - text: "La revisión"
        href: index.qmd
      - text: "Escalas"
        menu:
          - text: "Nacional"
            href: escalas/nacional.qmd
          - text: "Macro-zona"
            href: escalas/macro-zona.qmd
          - text: "Regional"
            href: escalas/regional.qmd
          - text: "Sectorial-regional"
            href: escalas/sectorial-regional.qmd
      - text: "Reportes"
        menu:
{nav}
      - text: "Explorar"
        href: explorar.qmd
      - text: "Datos"
        href: datos.qmd
      - text: "Diseño"
        href: diseno.qmd
      - text: "Metodología"
        href: metodologia.qmd
  page-footer:
    left: "Fuente: Banco Central de Chile. Generado desde bcch-data-repo."
    right: "Los datos mandan sobre el texto."

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    include-before-body:
      - personal-nav.html
    toc: true
    toc-depth: 3
    df-print: paged
    include-in-header:
      - text: |
          <meta name="color-scheme" content="light dark">
    fig-responsive: true
"""


def personal_site_nav() -> str:
    """Slate bar linking back to the personal site, on every page.

    Matches the convention already established by gpim_explorer/index.html --
    same ground (#1e293b), same muted link colour (#94a3b8), same emphasised
    home link -- so this section reads as part of dpolancon.github.io rather
    than a separate website that happens to be hosted alongside it.

    Links point at the SPANISH pages, because the programme is Spanish-only and
    those pages exist: research_es, talks_es, teaching_es, year-archive-es.
    Colours are literal rather than tokenised: this bar is deliberately the one
    element that does NOT follow the page theme, exactly as it does not on the
    rest of the personal site.
    """
    base = SITE_HOST
    links = [(f"{base}{ruta}", texto) for ruta, texto in SITE_HOST_LINKS]
    items = "\n".join(f'<a href="{href}">{text}</a>' for href, text in links)
    return f"""<style>
.personal-site-nav {{
  background: #1e293b;
  padding: 0.7rem 2rem;
  display: flex;
  align-items: center;
  gap: 1.5rem;
  flex-wrap: wrap;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
}}
.personal-site-nav a {{
  color: #94a3b8;
  text-decoration: none;
  font-size: 0.85rem;
  transition: color 0.15s;
}}
.personal-site-nav a:hover,
.personal-site-nav a:focus-visible {{ color: #fff; }}
.personal-site-nav a.nav-home {{
  font-weight: 700;
  font-size: 0.95rem;
  color: #f1f5f9;
  margin-right: auto;
}}
</style>
<nav class="personal-site-nav" aria-label="Sitio personal">
<a href="{base}/" class="nav-home">{SITE_HOST_NOMBRE}</a>
{items}
</nav>
"""


def styles_css() -> str:
    """Minimal theme additions: readable tables and scrollable wide content."""
    return """/* GENERATED by scripts/10_generate_site.py -- do not edit by hand. */

/* Wide tables scroll inside their own box rather than pushing the page. */
.table-responsive, .cell-output-display > table, div.quarto-figure {
  overflow-x: auto;
  max-width: 100%;
}

/* Línea de fuente. Va bajo cada exhibit, en cuerpo menor pero legible: es
   parte del material citable, no una nota al pie decorativa. */
.fuente {
  font-size: 0.85rem;
  line-height: 1.5;
  opacity: 0.78;
  border-top: 1px solid rgba(128, 128, 128, 0.22);
  padding-top: 0.5rem;
  margin: 0.4rem 0 1.8rem;
}
.fuente p { margin: 0; }

/* Distintivos de escala. La escala de observación es la afirmación central
   de la revisión, así que a qué unidad se refiere una cifra debe leerse sin
   entrar al texto. Cuatro escalas, de la más agregada a la más fina. */
.escala {
  display: inline-block;
  font-size: 0.75rem;
  font-weight: 600;
  letter-spacing: 0.04em;
  padding: 0.15rem 0.5rem;
  border-radius: 999px;
  vertical-align: middle;
}
.esc-nac { background: #7c3aed22; color: #6d28d9; border: 1px solid #7c3aed55; }
.esc-zon { background: #0891b222; color: #0e7490; border: 1px solid #0891b255; }
.esc-reg { background: #0d948822; color: #0f766e; border: 1px solid #0d948855; }
.esc-sec { background: #65a30d22; color: #4d7c0f; border: 1px solid #65a30d55; }

/* A standing caveat block. Used wherever imputed rent or zone-vs-region
   aggregation is in play -- these are not footnotes, they are load-bearing. */
.caveat {
  border-left: 3px solid #d97706;
  background: #d9770611;
  padding: 0.75rem 1rem;
  margin: 1.25rem 0;
  border-radius: 0 4px 4px 0;
}
.caveat strong { color: #b45309; }

/* ---- Explorer controls -------------------------------------------------
   The explorer runs on vendored Observable Plot plus plain JS rather than
   Quarto's OJS, so its controls are ordinary form elements and need styling
   that the Quarto theme does not provide. */
.explorer {
  display: flex;
  flex-direction: column;
  gap: 1rem;
  margin: 1.5rem 0;
  padding: 1rem 1.15rem;
  border: 1px solid rgba(128, 128, 128, 0.28);
  border-radius: 4px;
}
.ctl { display: flex; flex-direction: column; gap: 0.45rem; }
.ctl-label {
  font-size: 0.78rem;
  font-weight: 600;
  letter-spacing: 0.06em;
  text-transform: uppercase;
  opacity: 0.65;
}
.ctl-group { display: flex; flex-wrap: wrap; gap: 0.3rem 1.1rem; }
.ctl-group label {
  display: inline-flex;
  align-items: center;
  gap: 0.35rem;
  font-size: 0.9rem;
  cursor: pointer;
  margin: 0;
}
.ctl-regions label { min-width: 12.5rem; }
.ctl-actions { display: flex; gap: 0.5rem; margin-top: 0.15rem; }
.ctl-actions button {
  font: inherit;
  font-size: 0.8rem;
  padding: 0.2rem 0.7rem;
  border: 1px solid rgba(128, 128, 128, 0.45);
  border-radius: 3px;
  background: transparent;
  color: inherit;
  cursor: pointer;
}
.ctl-actions button:hover { border-color: currentColor; }
.ctl-actions button:focus-visible { outline: 2px solid currentColor; outline-offset: 2px; }

/* Charts scroll inside their own box; the page never scrolls sideways. */
.plotbox { overflow-x: auto; margin: 1rem 0 0.4rem; }
.plotbox svg { max-width: 100%; height: auto; }
.plotnote { font-size: 0.85rem; opacity: 0.7; margin: 0 0 1.5rem; }
.ploterr {
  font-size: 0.9rem;
  padding: 0.8rem 1rem;
  border-left: 3px solid #d97706;
  background: rgba(217, 119, 6, 0.08);
}
"""


def record_asset(path: Path) -> dict:
    """Manifest entry for a file already sitting where it is published.

    Used for the vendored chart libraries: they live in the site worktree by
    design, so copying them would mean copying a file onto itself.
    """
    return {
        "source": str(path),
        "published": path.name,
        "sha256": sha256(path),
        "bytes": path.stat().st_size,
    }


def copy_asset(src: Path, dest_dir: Path) -> dict:
    """Copy one asset into the site and return its provenance record."""
    dest_dir.mkdir(parents=True, exist_ok=True)
    dest = dest_dir / src.name
    shutil.copy2(src, dest)
    return {
        "source": str(src),
        "published": dest.name,
        "sha256": sha256(src),
        "bytes": src.stat().st_size,
    }


def es(value: float, decimals: int = 2) -> str:
    """Format a number the way Spanish writes it: comma as decimal separator.

    The site is Spanish-only, and a page that mixes "0,236" in hand-written
    prose with "0.2364" in an interpolated statistic reads as two documents
    stitched together. Every generated figure goes through here.
    """
    return f"{value:,.{decimals}f}".replace(",", "\u00a0").replace(".", ",")


def es_pct(fraction: float, decimals: int = 2) -> str:
    """Format a fraction as a Spanish-formatted percentage, without the sign."""
    return es(fraction * 100, decimals)


def escala_badge(escala: str) -> str:
    """Distintivo con la escala de observación y su unidad.

    Codifica algo verdadero y no decorativo: a qué unidad se refiere cada
    número de la página. Cruzar escalas sin decirlo es la forma más fácil de
    engañar a un lector, así que la escala viaja en el encabezado.
    """
    nombre, unidad = families_lib.ESCALA_LABEL[escala]
    clase = ESCALA_CLASE[escala]
    return f'<span class="escala {clase}">{nombre} &middot; {unidad}</span>'


# Clase CSS por escala. El orden va de la unidad más agregada a la más fina.
ESCALA_CLASE = {
    families_lib.ESCALA_NACIONAL: "esc-nac",
    families_lib.ESCALA_ZONAL: "esc-zon",
    families_lib.ESCALA_REGIONAL: "esc-reg",
    families_lib.ESCALA_SECTORIAL_REGIONAL: "esc-sec",
}


AÑO_ELABORACION = "2026"

# Nombre completo de la fuente primaria, tal como debe citarse.
FUENTE_BDE = "la Base de Datos Estadísticos del Banco Central de Chile"


def fuente(
    csv: str | None = None,
    *,
    tamano: str | None = None,
    extra: str | None = None,
    raiz: bool = False,
) -> str:
    """Línea de fuente de una figura, tabla o panel.

    Sigue la convención que el equipo ya usa en la formulación --«elaboración
    propia en base a BCCh»-- y se genera desde acá y no a mano, para que no
    pueda faltar en un exhibit ni divergir entre uno y otro.

    `csv` enlaza la base que produce el exhibit. La línea de fuente sola no
    basta: lo que vuelve el material verificable por un tercero es poder
    descargar el dato que está detrás, y por eso la auditoría exige ambos.
    """
    partes = [
        f"**Fuente:** elaboración propia ({AÑO_ELABORACION}) en base a {FUENTE_BDE}."
    ]
    if extra:
        partes.append(extra.rstrip("."))
        partes[-1] += "."
    if csv:
        etiqueta = f"`{csv}`" + (f" · {tamano}" if tamano else "")
        prefijo = "datos" if raiz else "../datos"
        partes.append(f"Datos: [{etiqueta}]({prefijo}/{csv}).")
    return '::: {.fuente}\n' + " ".join(partes) + "\n:::\n"


def nota_herramientas_ia(crosswalk_md: str = "") -> str:
    """Apartado que separa las tres capas de autoría del material.

    Existe para que un lector pueda citar sin ambigüedad de procedencia: el
    dato es del Banco Central, las decisiones de método son del equipo, y las
    herramientas de navegación se construyeron con asistencia de IA. Sin esa
    separación no se distingue una decisión metodológica de un artefacto de la
    herramienta, y la duda contamina lo sustantivo.
    """
    cuerpo = f"""## Nota: herramientas de apoyo creadas con IA

Este sitio combina tres capas de autoría distintas y conviene no confundirlas.

**El dato es del Banco Central.** Todas las series provienen de {FUENTE_BDE}.
No hay serie construida, estimada ni interpolada en ninguna etapa: la ausencia
se reporta como ausencia.

**La elaboración es del proyecto.** Las decisiones de método son del equipo de
investigación: calcular participaciones sobre precios corrientes y no sobre
volumen encadenado, seleccionar series por parseabilidad de región y no por
capítulo del catálogo, y organizar la revisión por escala de observación.

**Las herramientas de apoyo se construyeron con asistencia de IA.** El censo
automatizado del catálogo, el crosswalk que aparece abajo, el explorador
interactivo y las rutinas de auditoría se desarrollaron con asistencia de
modelos de lenguaje. Se verifican contra la fuente primaria y son reproducibles
con los comandos publicados en cada página. La responsabilidad por el contenido
es de quienes firman.
"""
    if crosswalk_md:
        cuerpo += f"""
### Crosswalk: reporte, familia, códigos y panel

Permite rastrear cualquier cifra del sitio hasta el código de serie que la
origina.

{crosswalk_md}
"""
    return cuerpo


def caveat(text: str) -> str:
    """A standing caveat block, rendered the same way everywhere."""
    return f'::: {{.caveat}}\n{text}\n:::\n'
